version: "3.3"

services:
  web:
    image: libreddit/libreddit:latest
    restart: always
    container_name: "libreddit"
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://127.0.0.1:80>
      interval: 5m
      timeout: 3s
