version: "3.3"

services:
  web:
    image: libreddit/libreddit:latest
    restart: unless-stopped
    container_name: "libreddit"
    networks:
        static:
            ipv4_address: 172.0.0.26
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://127.0.0.1:80"]
      interval: 5m
      timeout: 3s

networks:
   static:
       external: true
